#!/bin/bash

test -z "$cpio_binary" && {
    echo >&2 "no \$cpio_binary set" 
    exit 1
}

case "$1" in
    -h|--help)
        $cpio_binary --help | sed 's/^ \([^[:space:]][^:]*\):\?$/\1:/'
        ;;

    *)
        $cpio_binary "$@"
        ;;
esac
